# Generated by Django 4.2 on 2025-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('startup', 'Startup (1-10)'), ('small', 'Small (11-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (201-1000)'), ('enterprise', 'Enterprise (1000+)'), ('corporation', 'Corporation'), ('llc', 'LLC'), ('partnership', 'Partnership'), ('nonprofit', 'Non-Profit')], max_length=20),
        ),
    ]
