# Generated by Django 4.2 on 2025-08-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1001-5000)'), ('enterprise', 'Enterprise (5000+)'), ('corporation', 'Corporation'), ('llc', 'LLC'), ('partnership', 'Partnership'), ('nonprofit', 'Non-Profit')], max_length=20),
        ),
    ]
