# Generated by Django 4.2 on 2025-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='annual_travel_volume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1001-5000)'), ('enterprise', 'Enterprise (5000+)'), ('corporation', 'Corporation'), ('llc', 'LLC'), ('partnership', 'Partnership'), ('nonprofit', 'Non-Profit')], max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='credit_rating',
            field=models.CharField(blank=True, choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB')], max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='current_airlines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='expansion_plans',
            field=models.CharField(blank=True, choices=[('Aggressive', 'Aggressive'), ('Moderate', 'Moderate'), ('Conservative', 'Conservative'), ('Rapid', 'Rapid'), ('Stable', 'Stable')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('Net 15', 'Net 15'), ('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 60', 'Net 60')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='preferred_class',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Economy Plus', 'Economy Plus'), ('Business', 'Business'), ('First', 'First Class'), ('Business/First', 'Business/First')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sustainability_focus',
            field=models.CharField(blank=True, choices=[('Very High', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='technology_integration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='travel_frequency',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Bi-weekly', 'Bi-weekly')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
