# Generated by Django 4.2 on 2025-08-11 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_company_annual_travel_volume_company_company_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='api.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('creation', 'Lead Created'), ('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('score_update', 'Score Updated'), ('assignment', 'Lead Assigned'), ('contact_made', 'Contact Made'), ('email_sent', 'Email Sent'), ('call_made', 'Call Made'), ('meeting_scheduled', 'Meeting Scheduled'), ('qualification', 'Lead Qualified'), ('disqualification', 'Lead Disqualified'), ('opportunity_created', 'Opportunity Created'), ('proposal_sent', 'Proposal Sent'), ('negotiation_started', 'Negotiation Started'), ('won', 'Lead Won'), ('lost', 'Lead Lost')], max_length=25)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('icon', models.CharField(choices=[('plus', 'Plus'), ('mail', 'Mail'), ('phone', 'Phone'), ('message-circle', 'Message Circle'), ('message-square', 'Message Square'), ('trending-up', 'Trending Up'), ('user', 'User'), ('check-circle', 'Check Circle'), ('x-circle', 'X Circle'), ('calendar', 'Calendar'), ('briefcase', 'Briefcase'), ('file-text', 'File Text'), ('handshake', 'Handshake'), ('trophy', 'Trophy'), ('x', 'X')], default='plus', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='api.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
