# Generated by Django 4.2 on 2025-08-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_leadnote_table'),
    ]

    operations = [
    ]
