# Generated by Django 4.2 on 2025-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_create_leadhistory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
