# Generated by Django 4.2 on 2025-08-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_opportunityactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='move_as_lead',
            field=models.BooleanField(default=False),
        ),
    ]
