# Generated by Django 4.2 on 2025-08-26 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_move_as_lead_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('mixed', 'Multi-Channel')], default='email', max_length=20)),
                ('target_industry', models.CharField(default='All', max_length=100)),
                ('subject_line', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('cta', models.CharField(max_length=255)),
                ('linkedin_type', models.CharField(blank=True, choices=[('message', 'Direct Message'), ('post', 'Post/Content'), ('connection', 'Connection Request')], max_length=20, null=True)),
                ('estimated_open_rate', models.FloatField(default=40.0)),
                ('estimated_click_rate', models.FloatField(default=10.0)),
                ('is_custom', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='User', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.campaigntemplate'),
        ),
    ]
