# Generated by Django 4.2 on 2025-09-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_campaigntemplate_emailcampaign_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('validity_period', models.CharField(default='30', max_length=10)),
                ('special_terms', models.TextField(blank=True)),
                ('delivery_method', models.CharField(default='email', max_length=20)),
                ('travel_frequency', models.CharField(default='monthly', max_length=20)),
                ('annual_booking_volume', models.CharField(blank=True, max_length=100)),
                ('projected_spend', models.CharField(blank=True, max_length=100)),
                ('preferred_routes', models.TextField(blank=True)),
                ('domestic_economy', models.IntegerField(default=60)),
                ('domestic_business', models.IntegerField(default=25)),
                ('international', models.IntegerField(default=15)),
                ('base_discount', models.CharField(blank=True, max_length=10)),
                ('route_discounts', models.JSONField(blank=True, default=list)),
                ('loyalty_benefits', models.JSONField(blank=True, default=dict)),
                ('volume_incentives', models.TextField(blank=True)),
                ('contract_duration', models.CharField(default='24', max_length=10)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('payment_terms', models.CharField(default='net_30', max_length=20)),
                ('settlement_type', models.CharField(default='bsp', max_length=20)),
                ('airline_concessions', models.TextField(blank=True)),
                ('corporate_commitments', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('priority_level', models.CharField(default='medium', max_length=20)),
                ('discount_approval_required', models.BooleanField(default=False)),
                ('revenue_manager_assigned', models.CharField(blank=True, max_length=100)),
                ('legal_approval_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_draft', to='api.opportunity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
