# Generated by Django 4.2 on 2025-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_proposaldraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='attachment_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='attachment_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
