# Generated by Django 4.2 on 2025-09-02 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_target_count_to_emailcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('email_sent', models.DateTimeField(auto_now_add=True)),
                ('first_opened', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('first_clicked', models.DateTimeField(blank=True, null=True)),
                ('last_clicked', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tracking', to='api.emailcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lead')),
            ],
            options={
                'unique_together': {('campaign', 'lead')},
            },
        ),
    ]
