# Generated by Django 4.2 on 2025-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_emailcampaign_target_leads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='target_leads',
            field=models.ManyToManyField(blank=True, to='api.lead'),
        ),
    ]
