
# Generated by Django 4.2 on 2025-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='cta_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
