# Generated by Django 4.2 on 2025-09-08 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_moved_to_opportunity_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
