# Generated by Django 4.2 on 2025-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_leadhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='is_custom',
        ),
        migrations.RemoveField(
            model_name='campaigntemplate',
            name='linkedin_type',
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='is_standard_layout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='channel_type',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='cta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='estimated_click_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='estimated_open_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='subject_line',
            field=models.CharField(default='Default Subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaigntemplate',
            name='target_industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject_line',
            field=models.CharField(default='Default Subject', max_length=255),
        ),
    ]
